CREATE DATABASE DBRIFA
GO
USE DBRIFA
GO
CREATE TABLE PERSONA (
    IDPER int  NOT NULL IDENTITY(1,1),
    NOMPER varchar(20)  NOT NULL,
    APEPER varchar(20)  NOT NULL,
    NUMPER char(9)  NOT NULL,
    ESTPER char(1),
    CONSTRAINT PERSONA_pk PRIMARY KEY  (IDPER)
);

-- Table: PREMIOS
CREATE TABLE PREMIOS (
    IDPRE int  NOT NULL IDENTITY(1,1),
    NOMPRE varchar(20)  NOT NULL,
    DESPRE varchar(40)  NOT NULL,
    TIKPRE char(4)  NOT NULL,
    IDTIK int  NOT NULL,
    CONSTRAINT PREMIOS_pk PRIMARY KEY  (IDPRE)
);

-- Table: SORTEO
CREATE TABLE SORTEO (
    IDSOR int  NOT NULL IDENTITY(1,1),
    IDPER int  NOT NULL,
    IDPRE int  NOT NULL,
    INTSOR int  NOT NULL,
    CONSTRAINT SORTEO_pk PRIMARY KEY  (IDSOR)
);

-- Table: TIKET
CREATE TABLE TIKET (
    IDTIK int  NOT NULL IDENTITY(1,1),
    NUMTIK char(4)  NOT NULL,
    IDPER int  NOT NULL,
    CONSTRAINT TIKET_pk PRIMARY KEY  (IDTIK)
);

-- foreign keys
-- Reference: PREMIOS_TIKET (table: PREMIOS)
ALTER TABLE PREMIOS ADD CONSTRAINT PREMIOS_TIKET
    FOREIGN KEY (IDTIK)
    REFERENCES TIKET (IDTIK);

-- Reference: SORTEO_PERSONA (table: SORTEO)
ALTER TABLE SORTEO ADD CONSTRAINT SORTEO_PERSONA
    FOREIGN KEY (IDPER)
    REFERENCES PERSONA (IDPER);

-- Reference: SORTEO_PREMIOS (table: SORTEO)
ALTER TABLE SORTEO ADD CONSTRAINT SORTEO_PREMIOS
    FOREIGN KEY (IDPRE)
    REFERENCES PREMIOS (IDPRE);

-- Reference: TIKET_PERSONA (table: TIKET)
ALTER TABLE TIKET ADD CONSTRAINT TIKET_PERSONA
    FOREIGN KEY (IDPER)
    REFERENCES PERSONA (IDPER);

-- End of file.

INSERT INTO PERSONA(NOMPER,APEPER,NUMPER) VALUES('edgard','carranza','923543564');

select * from PERSONA;